### ISSUE TITLE
Wrong Hangfire initialization

### ISSUE THREAD

**Issue by mav10** [mcctomsk/backend-frontend-template#9]
1. First of all there is no any example of use HangfireJobs so we can not understand that it doesn't work at all.
2. There is no transparency how to register Jobs and configure them - it must be more understandable.
3. If we follow comment part example in hangfire - we will down - as static Requiring manager doesn't work properly and we actually should use a manager resolved from DI. 
```
        // var therapySyncJobSettings = Configuration.GetSection(nameof(TherapyDataSyncJobSettings))
        //     .Get<HangFireJobSettings>();
        // RecurringJob.AddOrUpdate<TherapyDataSyncJob>(
        //     nameof(TherapyDataSyncJob),
        //     job => job.Execute(),
        //     therapySyncJobSettings.CronExpression);
```

I'm going to push changes via PR to propose how to avoid these concerns.

**Comment by Shaddix** [comment]
@mav10 can we consider this one closed?

**Comment by mav10** [comment]
@Shaddix yep

as PR #10  has merged so we can close it
